# Generated by Django 3.1.3 on 2020-12-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=248)),
                ('Address', models.CharField(max_length=248)),
                ('Phone', models.CharField(max_length=248)),
                ('Payment', models.CharField(max_length=248)),
                ('Memo', models.TextField()),
            ],
            options={
                'db_table': 'PrintSettings',
            },
        ),
    ]
