# Generated by Django 3.1.3 on 2021-01-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_printsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintProductListSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preHtml', models.CharField(max_length=248)),
                ('suffixHtml', models.CharField(max_length=248)),
            ],
            options={
                'db_table': 'PrintProductListSettings',
            },
        ),
    ]
