# Generated by Django 3.1.3 on 2020-12-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(db_index=True, max_length=128)),
                ('Date', models.CharField(max_length=10)),
                ('Client', models.IntegerField()),
                ('WhetherPaid', models.BooleanField()),
                ('PaymentRecordPhoto', models.CharField(max_length=250)),
                ('Memo', models.TextField()),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-OrderID'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Address', models.CharField(max_length=248)),
                ('Phone', models.CharField(max_length=248)),
            ],
            options={
                'db_table': 'Client',
                'ordering': ['Name'],
                'unique_together': {('Name', 'Address', 'Phone')},
                'index_together': {('Name', 'Address', 'Phone')},
            },
        ),
    ]
