# Generated by Django 3.1.3 on 2020-12-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20201213_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.IntegerField()),
                ('Name', models.CharField(max_length=128)),
                ('Num', models.IntegerField()),
                ('Price', models.CharField(max_length=248)),
            ],
            options={
                'db_table': 'Item',
                'unique_together': {('OrderID', 'Name')},
                'index_together': {('OrderID', 'Name')},
            },
        ),
    ]
