# Generated by Django 3.1.3 on 2020-12-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='PaymentMemo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ShippingMemo',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ShippingStatus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
