# Generated by Django 3.1.3 on 2020-12-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20201219_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderID',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
